name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.0

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2022.1

    - name: Run go vet
      run: go vet ./...

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run tests
      run: go test -v ./...
